"""Add Managed Workspace Tables

Revision ID: 36391eefe9a1
Revises: 526e3a7c2204
Create Date: 2023-06-06 16:43:02.635745

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '36391eefe9a1'
down_revision = '526e3a7c2204'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('managed_workspace_account',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cid', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=True),
    sa.Column('org_unit_path', sa.String(length=120), nullable=False),
    sa.Column('can_self_serve', sa.Boolean(), nullable=True),
    sa.Column('workspace_account_id', sa.Integer(), nullable=True),
    sa.Column('is_account_enabled', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('managed_workspace_domain',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('facility', sa.String(length=4), nullable=True),
    sa.Column('is_enabled', sa.Boolean(), nullable=True),
    sa.Column('auto_assign_to_facility_staff', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('managed_workspace_account_domain',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account', sa.Integer(), nullable=True),
    sa.Column('domain', sa.Integer(), nullable=True),
    sa.Column('alias', sa.String(length=80), nullable=False),
    sa.ForeignKeyConstraint(['account'], ['managed_workspace_account.id'], name='fk_managed_workspace_ad_account_id'),
    sa.ForeignKeyConstraint(['domain'], ['managed_workspace_domain.id'], name='fk_managed_workspace_ad_domain_id'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('transfer_hold')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transfer_hold',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('controller', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('hold', mysql.VARCHAR(length=120), nullable=False),
    sa.Column('start_date', mysql.DATETIME(), nullable=True),
    sa.Column('end_date', mysql.DATETIME(), nullable=True),
    sa.Column('is_released', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('released_by_cid', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('created_by_cid', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('managed_workspace_account_domain')
    op.drop_table('managed_workspace_domain')
    op.drop_table('managed_workspace_account')
    # ### end Alembic commands ###
