"""Remove auto assign

Revision ID: 642eba032f93
Revises: bf3f90e925f6
Create Date: 2023-06-06 17:12:43.443243

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '642eba032f93'
down_revision = 'bf3f90e925f6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('managed_workspace_domain', 'auto_assign_to_facility_staff')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('managed_workspace_domain', sa.Column('auto_assign_to_facility_staff', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
