"""Add Managed Workspace Tables

Revision ID: bf3f90e925f6
Revises: 36391eefe9a1
Create Date: 2023-06-06 16:57:23.297474

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'bf3f90e925f6'
down_revision = '36391eefe9a1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('managed_workspace_account', 'org_unit_path')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('managed_workspace_account', sa.Column('org_unit_path', mysql.VARCHAR(length=120), nullable=False))
    # ### end Alembic commands ###
