AIR_TRAFFIC_MANAGER = 'ATM'
DEPUTY_AIR_TRAFFIC_MANAGER = 'DATM'
TRAINING_ADMINISTRATOR = 'TA'
FACILITY_ENGINEER = 'FE'
EVENT_COORDINATOR = 'EC'
WEBMASTER = 'WM'
INSTRUCTOR = 'INS'
MENTOR = 'MTR'

DICE_TEAM = 'DICE'
ACE_TEAM = 'ACE'

facility_staff_roles = [
    AIR_TRAFFIC_MANAGER,
    DEPUTY_AIR_TRAFFIC_MANAGER,
    TRAINING_ADMINISTRATOR,
    EVENT_COORDINATOR,
    FACILITY_ENGINEER,
    WEBMASTER,
    INSTRUCTOR,
    MENTOR
]

facility_unique_roles = [
    AIR_TRAFFIC_MANAGER,
    DEPUTY_AIR_TRAFFIC_MANAGER,
    TRAINING_ADMINISTRATOR,
    EVENT_COORDINATOR,
    FACILITY_ENGINEER,
    WEBMASTER,
]

vatusa_staff_roles = [
    'US1',
    'US2',
    'US3',
    'US4',
    'US5',
    'US6',
    'US7',
    'US8',
    'US9',
]
